routes/front.php
<?php
use App\Http\Controllers\AuthController;
use App\Http\Middleware\FrontMiddleware;
use Illuminate\Support\Facades\Route;


Route::middleware([FrontMiddleware::class])->group(function (){
    Route::get('/frontlogin',    [AuthController::class, 'showLoginForm'])->name('frontlogin');
    Route::post('/frontlogin_process',    [AuthController::class, 'login'])->name('frontlogin_process');
    Route::get('/frontregister',    [AuthController::class, 'showRegisterForm'])->name('frontregister');
    Route::post('/frontregister_process',    [AuthController::class, 'register'])->name('frontregister_process');
});
Route::get('/frontlogout',    [AuthController::class, 'logout'])->name('frontlogout')->middleware('auth:front');

routes/web.php
<?php
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\MainController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CommentController as CommentControllerFront;
use App\Http\Controllers\ContactController as ContactControllerFront;
use App\Http\Controllers\StarRatingController as StarRatingControllerFront;
use App\Http\Controllers\EmailVerifyController;
use App\Http\Controllers\PostController as PostControllerFront;
use App\Http\Controllers\SubscribeController as SubscribeControllerFront;
use App\Http\Controllers\CategoryController as CategoryControllerFront;
use App\Http\Controllers\TagController as TagControllerFront;
use App\Http\Controllers\SearchController as SearchControllerFront;
use App\Http\Controllers\TestController;
use App\Http\Controllers\UserController;

use App\Models\User;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\View;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// front
Route::get('/',                 [PostControllerFront::class, 'index'])->name('home');
Route::post('/subscribe ',      [SubscribeControllerFront::class, 'subscribe'])->name('subscribe');
Route::get('/article/{slug}',   [PostControllerFront::class, 'show'])->name('posts.single');
Route::get('/category/{slug}',  [CategoryControllerFront::class,  'show'])->name('categories.single');
Route::get('/tag/{slug}',       [TagControllerFront::class,       'show'])->name('tags.single');
Route::get('/search',           [SearchControllerFront::class,    'index'])->name('search');
Route::post('/comment/{slug}',  [CommentControllerFront::class,    'saveComment'])->name('comment');
Route::resource('contact-form',  ContactControllerFront::class);


Route::post('/star-rating',  [StarRatingControllerFront::class, 'starRating'])->name('starrating');


// Эти страницы доступны только админу -> 'middleware' => 'admin' - 'namespace' => 'Admin',
Route::group(['prefix' => 'admin', 'middleware' => ['admin', 'verified']], function () {
    Route::get('/',     [MainController::class, 'index'])->name('admin.index');
    Route::resource('/categories',CategoryController::class);
    Route::resource('/tags',TagController::class);
    Route::resource('/posts', PostController::class);
});


Route::group(['middleware' => 'guest'], function () {
    Route::get('/register',  [UserController::class, 'create'])->name('register.create');
    Route::post('/register', [UserController::class, 'store'])->name('register.store');
    Route::get('/login',     [UserController::class, 'loginForm'])->name('login.create');
    Route::post('/login',    [UserController::class, 'login'])->name('login');
});
// К 'logout' будут иметь доступ только авторизованные пользователи '->middleware('auth')'
Route::get('/logout',  [UserController::class, 'logout'])->name('logout')->middleware('auth:web');


Route::get('/email/verify', [EmailVerifyController::class, 'verificationNotice'])->middleware(['auth'])->name('verification.notice');
Route::post('/email/verification-notification', [EmailVerifyController::class, 'verificationLinkSent'])->middleware(['auth', 'throttle:6,1'])->name('verification.send');
Route::get('/email/verify/{id}/{hash}', [EmailVerifyController::class, 'verificationVerify'])->middleware(['auth', 'signed'])->name('verification.verify');













Route::get('/test/create', [TestController::class, 'create'])->name('test.create');
Route::post('/test', [TestController::class, 'store'])->name('test');
Route::get('/testp', [TestController::class, 'testp'])->name('testp')->middleware('auth');

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\CategoryModel;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        $categories = CategoryModel::query()->paginate(6);
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
        ]);
        CategoryModel::query()->create($request->all());
        $request->session()->flash('success', 'Категория добавлена');
        return redirect()->route('categories.index')->with('success', 'Категория добавлена');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return string
     */
    public function edit($id)
    {
        $category = CategoryModel::query()->find($id);

        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required',
        ]);

        $category = CategoryModel::query()->find($id);
        /*
         * slug менять не желателно потому что он уже индексирован но если все равно хотите менять slug надо писать, $category->slug = null;
         * типа сначало обнуляем slug потом заново перезаписываем. Это заставит пакета laravel sluggable сгенерировать новый slug
         *
         * !!! $category = CategoryModel::query()->find($id)->update($request->all());
         * !!! $category->slug = null;
         * !!! Если писать таким образом то slug не будет работать.
         *
        */
        $category->slug = null;
        $category->update($request->all());
        return redirect()->route('categories.index')->with('success', 'Изменения сохранены');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {

        /*
         * $category = Category::find($id);
         * $category->delete();
         *
         * или с одной стракой кода - CategoryModel::destroy($id);
        */
        $category = CategoryModel::find($id);
        if ($category->posts->count()) {
            return redirect()->route('categories.index')->with('error', 'Ошибка! У категории есть записи');
        }
        //CategoryModel::destroy($id);
        $category->delete();
        return redirect()->route('categories.index')->with('success', 'Категория удалена');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\CategoryModel;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function show($slug)
    {
        $category = CategoryModel::query()->where('slug', $slug)->firstOrFail();
        $posts = $category->posts()->orderBy('id', 'desc')->paginate(2);
        return view('categories.show', compact('category', 'posts'));
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.layout')

@section('content')
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Категории</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Blank Page</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Создание категории</h3>
                            </div>
                            <!-- /.card-header -->

                            <form role="form" method="post" action="{{ route('categories.store') }}">
                                @csrf
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="title">Название</label>
                                        <input type="text" name="title"
                                               class="form-control @error('title') is-invalid @enderror" id="title"
                                               placeholder="Название">
                                    </div>
                                </div>
                                <!-- /.card-body -->

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Сохранить</button>
                                </div>
                            </form>

                        </div>
                        <!-- /.card -->

                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.layout')

@section('content')
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Обновление категории</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Blank Page</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Категория {{ $category->title }}</h3>
                            </div>
                            <!-- /.card-header -->

                            <form role="form" method="post" action="{{ route('categories.update', ['category' => $category->id]) }}">
                                @csrf
                                @method('PUT')
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="title">Название</label>
                                        <input type="text" name="title"
                                               class="form-control @error('title') is-invalid @enderror" id="title"
                                               value="{{ $category->title }}">
                                    </div>
                                </div>
                                <!-- /.card-body -->

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Обновить</button>
                                </div>
                            </form>

                        </div>
                        <!-- /.card -->

                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.layout')

@section('content')
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Категории</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Blank Page</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Список категорий</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <a href="{{ route('categories.create') }}" class="btn btn-primary mb-3">Добавить
                                    категорию</a>
                                @if (count($categories))
                                    <div class="table-responsive">
                                        <table class="table table-bordered table-hover text-nowrap">
                                            <thead>
                                            <tr>
                                                <th style="width: 30px">#</th>
                                                <th>Наименование</th>
                                                <th>Slug</th>
                                                <th>Actions</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($categories as $category)
                                                <tr>
                                                    <td>{{ $category->id }}</td>
                                                    <td>{{ $category->title }}</td>
                                                    <td>{{ $category->slug }}</td>
                                                    <td>
                                                        <a href="{{ route('categories.edit', ['category' => $category->id]) }}" class="btn btn-info btn-sm float-left mr-1">
                                                            <i class="fas fa-pencil-alt"></i>
                                                        </a>

                                                        <form action="{{ route('categories.destroy', ['category' => $category->id]) }}" method="post" class="float-left">
                                                            @csrf
                                                            @method('DELETE')
                                                            <button type="submit" class="btn btn-danger btn-sm"
                                                                    onclick="return confirm('Подтвердите удаление')">
                                                                    <i class="fas fa-trash-alt"></i>
                                                            </button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                    </div>

                                @else
                                    <p>Категорий пока нет...</p>
                                @endif

                                <div class="card-footer clearfix">
                                    {{--php artisan vendor:publish --tag=laravel-pagination--}}
                                    {{ $categories->links('vendor.pagination.bootstrap-4') }}
                                    {{--<ul class="pagination pagination-sm m-0 float-right">
                                        <li class="page-item"><a class="page-link" href="#">«</a></li>
                                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                                        <li class="page-item"><a class="page-link" href="#">»</a></li>
                                    </ul>--}}
                                </div>
                            </div>
                            <!-- /.card-body -->

                        </div>
                        <!-- /.card -->

                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
@endsection